config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :bookings
  get 'home', to: 'pages#home'
  post 'home', to: 'pages#home' #post request for the button
  get 'gallery', to: 'pages#gallery'
  get 'rooms', to: 'pages#rooms'
  get 'location', to: 'pages#location'
  get 'availability', to: 'pages#availability'
  post 'availability', to: 'pages#availability' #post request for the button
  get 'breakfast', to: 'pages#breakfast'
  get 'specials', to: 'pages#specials'

  root to: 'pages#home' #set homepage
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
	validates_presence_of :booking_date
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  layout "bookings"

  #petergate
  #access all: [:show, :index], user: {except: [:destroy]}, company_admin: :all
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to bookings_url, notice: 'Booking was successfully created.' }
        # format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        # format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        # format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        # format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully deleted.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:booking_date, :deluxe_room, :double_room, :single_room, :twin_room, :deluxebooker, :doublebooker, :twinbooker, :singlebooker)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
<% if booking.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

  <ul>
    <% booking.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="col-sm-6">
    <div class="entry-section card card-body">
      <div class="field form-group">
        <%= form.label :booking_date %><br>
        <%= form.text_field :booking_date, id: :booking_booking_date, type: "date", required: "required", class: "form-control" %>
      </div>
    </div>


    <div class="entry-section card card-body">
      <div class="field form-group">
        <%= form.label :deluxe_room %>
        <%= form.check_box :deluxe_room, id: :booking_deluxe_room %>
      </div>
      <div class="field form-group">
        Name &amp; Contact of Booker<br>
        <%= form.text_field :deluxebooker, id: :booking_deluxebooker, class: "form-control" %>
      </div>
    </div>


    <div class="entry-section card card-body">
      <div class="field form-group">
        <%= form.label :double_room %>
        <%= form.check_box :double_room, id: :booking_double_room %>
      </div>
      <div class="field form-group">
        Name &amp; Contact of Booker<br>
        <%= form.text_field :doublebooker, id: :booking_doublebooker, class: "form-control" %>
      </div>
    </div>


    <div class="entry-section card card-body">
      <div class="field form-group">
        <%= form.label :single_room %>
        <%= form.check_box :single_room, id: :booking_single_room %>
      </div>
      <div class="field form-group">
        Name &amp; Contact of Booker<br>
        <%= form.text_field :singlebooker, id: :booking_singlebooker, class: "form-control" %>
      </div>
    </div>


    <div class="entry-section card card-body">
      <div class="field form-group">
        <%= form.label :twin_room %>
        <%= form.check_box :twin_room, id: :booking_twin_room %>
      </div>
      <div class="field form-group">
        Name &amp; Contact of Booker<br>
        <%= form.text_field :twinbooker, id: :booking_twinbooker, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="col-sm-6"></div>
</div>

<div class="row margin-top">
  <div class="col-sm-6">
    <p style="color: #640000">* Rember to provide a booker's name for every checked room and viseversa</p>

    <div class="actions">
      <%= form.submit class: "btn btn-4 btn-block margin-top" %>
    </div>
  </div>

  <div class="col-sm-6"></div>
</div>

<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table id="example" class="display" style="width:100%">
  <thead>
    <tr>
      <th>Booking date</th>
      <th>Deluxe room</th>
      <th>Double room</th>
      <th>Single room</th>
      <th>Twin room</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.booking_date %></td>
        <td>
          <% if booking.deluxe_room %>
            <span style="color: maroon;"><strong>BOOKED!</strong></span><br>
            <!-- Show booker if booked -->
            <%= booking.deluxebooker %>
          <% else %>
            <span style="color: green;">Available</span>
          <% end %>
        </td>
        <td>
          <% if booking.double_room %>
            <span style="color: maroon;"><strong>BOOKED!</strong></span><br>
            <%= booking.doublebooker %>
          <% else %>
            <span style="color: green;">Available</span>
          <% end %>
        </td>
        <td>
          <% if booking.single_room %>
            <span style="color: maroon;"><strong>BOOKED!</strong></span><br>
            <%= booking.singlebooker %>
          <% else %>
            <span style="color: green;">Available</span>
          <% end %>
        </td>
        <td>
          <% if booking.twin_room %>
            <span style="color: maroon;"><strong>BOOKED!</strong></span><br>
            <%= booking.twinbooker %>
          <% else %>
            <span style="color: green;">Available</span>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Delete', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
      <tr>
        <th>Booking date</th>
        <th>Deluxe room</th>
        <th>Double room</th>
        <th>Single room</th>
        <th>Twin room</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
  </tfoot>
</table>

<hr>
<p style="color: #640000;">Hint: Type name of booker in search box to view only their bookings</p>
<hr>

<%= link_to '+ New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Booking date:</strong>
  <%= @booking.booking_date %>
</p>
<hr>

<p>
  <strong>Deluxe room:</strong>
  <%= @booking.deluxe_room %>
</p>
<p>
  <strong>Deluxe room Booker:</strong>
  <%= @booking.deluxebooker %>
</p>
<hr>

<p>
  <strong>Double room:</strong>
  <%= @booking.double_room %>
</p>
<p>
  <strong>Double room Booker:</strong>
  <%= @booking.doublebooker %>
</p>
<hr>

<p>
  <strong>Single room:</strong>
  <%= @booking.single_room %>
</p>
<p>
  <strong>Single room Booker:</strong>
  <%= @booking.singlebooker %>
</p>
<hr>

<p>
  <strong>Twin room:</strong>
  <%= @booking.twin_room %>
</p>
<p>
  <strong>Twin room Booker:</strong>
  <%= @booking.twinbooker %>
</p>
<hr>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>