config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :bookings
  get 'home', to: 'pages#home'
  post 'home', to: 'pages#home' #post request for the button
  get 'gallery', to: 'pages#gallery'
  get 'rooms', to: 'pages#rooms'
  get 'location', to: 'pages#location'
  get 'availability', to: 'pages#availability'
  post 'availability', to: 'pages#availability' #post request for the button
  get 'breakfast', to: 'pages#breakfast'
  get 'specials', to: 'pages#specials'

  root to: 'pages#home' #set homepage
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/availability.html.erb
<!-- AVAILABILTY OF ROOMS: BOOKING -->
<div class="container-fluid location-section largepadding dark belownav">
	<h1 class="white">Booking</h1>
	<h3>Room Availability</h3>
</div>

<div class="container-fluid largepadding availability-section">

	<div class="row">
		<div class="col-sm-12">
			<h3>Rooms available for the dates you selected</h3>	
			<table class="table table-striped dates-table">
				<thead>
					<tr>
						<th><p>Selected Dates</p></th>
						<th><p>Deluxe</p></th>
						<th><p>Double</p></th>
						<th><p>Single</p></th>
						<th><p>Twin</p></th>
					</tr>
				</thead>
				<tbody>
					<% $selected_dates_ar.each do |selected_date| %>
					<tr>
						<td>
							<%= Date.strptime(selected_date[:booking_date].to_s, '%Y%m%d').strftime("%d %b %Y") %>
						</td>
						<td>
							<% if selected_date[:deluxe_room] %>
							<span class="booked-room">Taken</span>
							<% else %>
							<span class="available-room">AVAILABLE</span>
							<% end %>
						</td>
						<td>
							<% if selected_date[:double_room] %>
							<span class="booked-room">Taken</span>
							<% else %>
							<span class="available-room">AVAILABLE</span>
							<% end %>
						</td>
						<td>
							<% if selected_date[:single_room] %>
							<span class="booked-room">Taken</span>
							<% else %>
							<span class="available-room">AVAILABLE</span>
							<% end %>
						</td>
						<td>
							<% if selected_date[:twin_room] %>
							<span class="booked-room">Taken</span>
							<% else %>
							<span class="available-room">AVAILABLE</span>
							<% end %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<hr>
		</div>
	</div>

	<div class="row margin-top">
		<div class="col-sm-6 tariffs">			
			<div class="col-sm-12">
				<h3>Accommodation Tariffs</h3>	
				<table class="table">
					<thead>
						<tr>
							<th><p>Room Type</p></th>
							<th><p>Double occupancy</p></th>
							<th><p>Single occupancy</p></th>
							<th><p>Tripple occupancy</p></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Deluxe</td>
							<td>USD 70</td>
							<td>USD 50</td>
							<td>USD 100</td>
						</tr>
						<tr>
							<td>Standard Double</td>
							<td>USD 60</td>
							<td>USD 55</td>
							<td> - </td>
						</tr>
						<tr>
							<td>Twin room</td>
							<td>USD 50</td>
							<td>USD 45</td>
							<td> - </td>
						</tr>
						<tr>
							<td>Single room</td>
							<td>USD 45</td>
							<td>USD 40</td>
							<td> - </td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="col-md-12">
				<h3>Payment Methods</h3>
				Visa, American Express, Pay in local currency or dollars at the property.
			</div>
		</div> 

		<div class="col-sm-6">
			<%= form_tag availability_path, name: "form1" do %>
			<div class="row margin-top">
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<p class="form-headings">Full Name:</p>
								<input type="text" class="form-control input-lg" name="fullname" id="fullname" required="required">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<p class="form-headings">Phone:</p>
								<input type="text" class="form-control input-lg" name="phone" id="phone" required="required">
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<p class="form-headings">Adults:</p>
								<select class="form-control" name="adults">
									<option>1</option>
									<option>2</option>
									<option>3</option>
									<option>4</option>
									<option>5</option>
									<option>6</option>
									<option>7</option>
									<option>8</option>
									<option>9</option>
									<option>10</option>
								</select>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<p class="form-headings">Children:</p>
								<select class="form-control" name="children">
									<option>0</option>
									<option>1</option>
									<option>2</option>
									<option>3</option>
									<option>4</option>
									<option>5</option>
									<option>6</option>
									<option>7</option>
									<option>8</option>
									<option>9</option>
									<option>10</option>
								</select>
							</div>
						</div>
					</div>
					
					<div class="row room-types">
						<div class="col-md-12">
							<div class="form-group">
								<p class="form-headings">Room Types:</p>
								<div class="row">
									<div class="col-md-6">
										<input type="checkbox" name="deluxe_chx" value="1"> Deluxe room<br>
										<input type="checkbox" name="double_chx" value="1"> Standard Double<br>
									</div>
									<div class="col-md-6">
										<input type="checkbox" name="twin_chx" value="1"> Twin room<br>
										<input type="checkbox" name="single_chx" value="1"> Single room<br>
									</div>
								</div>
							</div>
						</div>
					</div> 

					<div class="row">
						<div class="col-md-12">
							<%= submit_tag 'Book Now', class: "btn btn-4 btn-block margin-top" %>
						</div>							
					</div>
				</div> 
			</div>
			<% end %>
		</div>	
	</div>

	<div class="row margin-top">
		<div class="col-sm-12">
			<div class="card card-body">
				<p><%= link_to "Learn More about our Rooms", rooms_path %></p>
				<p>Detailed information about each Room</p>
			</div>
		</div>
	</div>

	<div class="row tocs margin-top">
		<div class="col-sm-12">
			<div class="card card-body">
				<h3>Terms and Conditions</h3>

				<p>Children and extra beds</p>
				<ul>
					<li>One child below age 6 may stay free of charge when using existing bed.</li>
					<li>One child may stay at the price of 50 % of the room stay per person per night in an extra bed.</li>
					<li>Older children/adults may stay at the price of 100 % of the room stay per person per night in an extra bed.</li>
					<li>There are no cribs provided in a room</li>
				</ul>

				<p>All prices are Per Room Per Night inclusive of Bed &amp; Breakfast</p>

				<p>Exchange rate: UGX 3600 for USD 1 and USD 1 for UGX 3500</p>

				<p>Check-in: from 10:00-22:00 hours</p>

				<p>Check-out: until 10:00 hours</p>

				<p><i>Stay with us Feel like Family</i></p>
			</div>
		</div>
	</div>
</div>

app/views/pages/breakfast.html.erb
<div class="container-fluid breakfast-section largepadding dark belownav">
	<h1 class="white house-icon">Breakfast</h1>
	<h3>Breakfast at Sheevy's Bed and Breakfast is the start of a new day, a celebration.</h3>
</div>

<div class="side-by-side-example">
	<div class="row d-flex h-100">
		<div class="col-sm-6 nopadding">
			<%= image_tag "egg.jpg" %>
		</div>
		<div class="col-sm-6 justify-content-center align-self-center" style="padding: 30px">
			<p>With smiles, we serve a delicious breakfast. It starts with brewed coffee, herbal and breakfast teas, wonderfully awakening juices and fresh tropical fruits to get you ready for the main course. Most of these are picked from our backyard garden.</p>
			<p>For each meal we create wonderfully seasoned egg dishes as well as a vegetable side and sometimes we serve our home made bread occasionally accented by tasty breakfast meats.</p>
			<p>Sometimes we switch things up and prepare French toast, pancakes or our local delicacy katogo.</p>
			<p>Not a breakfast eater? We may convert you.</p>
			<p>However, if you would prefer something different please let us know we can make it happen.</p>
			<p>It is our delight to start each day with our guests preparing for you a celebration and a break of your slumbering fast.</p>
		</div>
	</div>
</div>

<div class="side-by-side-example">
	<div class="row d-flex h-100">
		<div class="col-sm-6 justify-content-center align-self-center" style="padding: 30px">
			<p>We know some people don’t like to talk much in the morning, so we offer a group table as well as individual dining arrangements in our lovely garden.</p>
			<p>Our breakfast is served between 7:00 and 10:00a.m daily.</p>
			<p>For business travellers and early risers we can abbreviate your meal and or customise departure times. It’s all about our guests.	</p>
		</div>
		<div class="col-sm-6 nopadding">
			<%= image_tag "fruits.jpg" %>
		</div>
	</div>
</div>

app/views/pages/gallery.html.erb
<!-- GALLERY -->
<div class="container-fluid gallery-section largepadding belownav" id="gallery">
	<!-- Images used to open the lightbox -->
	<% image_index = 1 %>
	<% #@image_rows.times do %> 
	<% #end %> 
	<div class="row"> 
		<% @image_files.each do |image_file| %> 
			<!-- Check if file exists first -->
			<% if FileTest.exist?("#{Rails.root}/app/assets/images/gallery/"+image_file.split("/").pop) %>
				<div class="col-sm-3">
					<%= image_tag "gallery/"+image_file.split("/").pop, onclick: "openModal();currentSlide(#{image_index})", class: "hover-shadow" %>
					<% image_index += 1 %>
				</div>				
			<% end %>					
		<% end %>
	</div>
	
	<!-- The Modal/Lightbox -->
	<div id="myModal" class="modal">
		<span class="close cursor" onclick="closeModal()">&times;</span>
		<div class="modal-content">

			<!-- <div class="mySlides">
				<div class="numbertext">1</div>
				<img src="images/gallery/1.jpg" style="width:100%">
			</div> -->
			<% image_index = 1 %>
			<% @image_files.each do |image_file| %> 
				<!-- Check if file exists first -->
				<% if FileTest.exist?("#{Rails.root}/app/assets/images/gallery/"+image_file.split("/").pop) %>
					<div class="mySlides">
						<div class="numbertext"><%= image_index %></div>
						<%= image_tag "gallery/"+image_file.split("/").pop, class: "gallery-main-image" %>
						<% image_index += 1 %>
					</div>			
				<% end %>					
			<% end %>

			<!-- Next/previous controls -->
			<a class="prev" onclick="plusSlides(-1)">&#10094;</a>
			<a class="next" onclick="plusSlides(1)">&#10095;</a>

			<div style="display: none;">
				<!-- Caption text -->
				<div class="caption-container">
					<p id="caption"></p>
				</div>
				<!-- Thumbnail image controls -->
				<div class="column">
					<%= image_tag "logo.png", onclick: "currentSlide(1)", width: 200, class: "demo" %>
				</div>
				<div class="column">
					<%= image_tag "logo.png", onclick: "currentSlide(2)", width: 200, class: "demo" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/location.html.erb
<!-- LOCATION -->
<div class="container-fluid location-section largepadding dark belownav" id="location">
	<h1 class="white">Location</h1>
	<h3>Sheevys is located about 10 minutes from Fort Portal town. There are markets, supermarkets   restaurants, a golf course and gyms close by.</h3>
	<p class="greydescription">Google Map</p>

	<div class="map-responsive">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d498.69738184958993!2d30.263039035764688!3d0.6274849638796907!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1763d0c564cbfa2d%3A0xb20e45f3a713c552!2sSheevy&#39;s+Bed+%26+Breakfast!5e0!3m2!1sen!2sug!4v1521737815793" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>

app/views/pages/rooms.html.erb
<!-- ROOMS BODY -->


<!-- ROOMS SECTION -->
<div class="container-fluid rooms-section largepadding dark belownav" id="rooms">
	<h1 class="white house-icon">The Rooms</h1>
	<!-- fa_icon "home"  -->
	<h3>Accomodation at Sheevys BNB</h3>
	
	<p class="greydescription">1 Deluxe Room | 1 Standard Double Room | 1 Twin Room | 1 Standard Single Room</p>

	<p class="greydescription"><strong>All rooms have wireless internet access</strong></p>
</div>
<!-- ...room photo and details -->
<div class="room-example">
	<div class="row d-flex h-100">
		<div class="col-sm-4 justify-content-center align-self-center" style="padding: 30px">
			<h2>DELUXE ROOM</h2>  		
			<p>Our exquisite and spacious: Deluxe room is fitted with a Queen Size bed and an ensuite bathroom. The room prides in complimentary coffee station, built in reading table, inbuilt wardrobe, and bottled drinking water. The room has a view of our fine-looking garden.</p>
			<p>We can give it as a Triple with an added single bed at an extra cost.</p>	
		</div>
		<div class="col-sm-8 nopadding">
			<%= image_tag "rooms/deluxe1.jpg" %>
		</div>
	</div>
</div>
<!-- ...room photo and details -->
<div class="room-example">
	<div class="row d-flex h-100">
		<div class="col-sm-4 justify-content-center align-self-center" style="padding: 30px">
			<h2>STANDARD DOUBLE ROOM</h2>
			<p>A Queen Size bed with a floor rug to ensure our guests comfort and warmth. The room has an ensuite spacious bathroom, fitted wardrobe, reading table and bottled water.</p>
		</div>
		<div class="col-sm-8 nopadding">
			<%= image_tag "rooms/standard_double1.jpg" %>
		</div>
	</div>
</div>
<!-- ...room photo and details -->
<div class="room-example">
	<div class="row d-flex h-100">
		<div class="col-sm-4 justify-content-center align-self-center" style="padding: 30px">
			<h2>SINGLE ROOM</h2>
			<p>The room has a Single Bed which is however, big enough to be shared at an extra charge. It prides with an ensuite spacious bathroom, reading table and a wardrobe.</p>
		</div>
		<div class="col-sm-8 nopadding">
			<%= image_tag "rooms/single1.jpg" %>
		</div>
	</div>
</div>
<!-- ...room photo and details -->
<div class="room-example">
	<div class="row d-flex h-100">
		<div class="col-sm-4 justify-content-center align-self-center" style="padding: 30px">
			<h2>TWIN ROOM</h2>
			<p>Our twin room has two single beds which are very comfy. It also has a fitted reading table, wardrobes complimentary bottled drinking water. Its spacious and elegant bathroom is not ensuite.</p>
		</div>
		<div class="col-sm-8 nopadding">
			<%= image_tag "rooms/twinroom.jpg" %>
		</div>
	</div>
</div>
<!-- ...room photo and details -->
<div class="room-example">
	<div class="row d-flex h-100">
		<div class="col-sm-4 justify-content-center align-self-center" style="padding: 30px">
			<h2>TRIPPLE ROOM</h2>
			<p>Our Deluxe Room can be given as a Triple with an added single bed at an extra cost.</p>	
		</div>
		<div class="col-sm-8 nopadding">
			<%= image_tag "rooms/trippleroom.jpg" %>
		</div>
	</div>
</div>

<div class="room-example" id="rates">
	<div class="row d-flex h-100">
		<div class="col-sm-4 justify-content-center align-self-center" style="padding: 30px">
			<h1>RATES</h1>
		</div>
		<div class="col-sm-8 tariffs">
			<table class="table">
				<thead>
					<tr>
						<th><p>Room Type</p></th>
						<th><p>Double occupancy</p></th>
						<th><p>Single occupancy</p></th>
						<th><p>Tripple occupancy</p></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Deluxe*</td>
						<td>USD 70</td>
						<td>USD 50</td>
						<td>USD 100</td>
					</tr>
					<tr>
						<td>Standard Double</td>
						<td>USD 60</td>
						<td>USD 55</td>
						<td> - </td>
					</tr>
					<tr>
						<td>Twin room</td>
						<td>USD 50</td>
						<td>USD 45</td>
						<td> - </td>
					</tr>
					<tr>
						<td>Single room</td>
						<td>USD 45</td>
						<td>USD 40</td>
						<td> - </td>
					</tr>
				</tbody>
			</table>

			<small>* The Deluxe Room can be given as a Triple Room (with an added single bed at an extra cost)</small>
		</div>
	</div>
</div>

app/views/pages/specials.html.erb
<div class="container-fluid specials-section largepadding dark belownav">
	<h1 class="white house-icon">Specials</h1>
	<h3>We've got a few special things just for you</h3>
</div>

<div class="container section-padding">
	<div class="row d-flex h-100 specials-row">
		<div class="col-sm-4">
			<%= image_tag "gift_certificate.jpg" %>	
		</div>
		<div class="col-sm-8 justify-content-center align-self-center" style="padding: 30px">
			<h3>Gift Certificate</h3>
			<p>This is a perfect gift to indulge yourself or your loved ones available in any denomination call email or stop by to purchase.</p>
		</div>
		<div class="col-sm-4">
			<%= image_tag "weekend.jpg" %>	
		</div>
		<div class="col-sm-8 justify-content-center align-self-center" style="padding: 30px">
			<h3>Weekend Getaway</h3>
			<p>Sweep your lover off their feet with a romantic getaway. This includes breakfast for two a bottle of wine in your room desserts before bed.</p>
		</div>
		<div class="col-sm-4">
			<%= image_tag "egg.jpg" %>	
		</div>
		<div class="col-sm-8 justify-content-center align-self-center" style="padding: 30px">
			<h3>Mouth watering breakfast</h3>
			<p>Take your family or friends for a Sheevys breakfast experience. Our home made breakfast with surprises for children</p>
			<p>
				<%= link_to 'See Breakfast Options', breakfast_path %>
			</p>
		</div>
	</div>
</div>