config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :bookings
  get 'home', to: 'pages#home'
  post 'home', to: 'pages#home' #post request for the button
  get 'gallery', to: 'pages#gallery'
  get 'rooms', to: 'pages#rooms'
  get 'location', to: 'pages#location'
  get 'availability', to: 'pages#availability'
  post 'availability', to: 'pages#availability' #post request for the button
  get 'breakfast', to: 'pages#breakfast'
  get 'specials', to: 'pages#specials'

  root to: 'pages#home' #set homepage
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- for search engine description -->
	<meta name="description" content="Sheevy's Bed and Breakfast: Uganda">
	
	<title><%= @page_title %></title>
	
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body data-spy="scroll" data-target=".navbar">
	<div class="main-body-container">
		
		<!-- NAV BAR -->
		<div class="container-fluid navbar-section">
			<nav class="navbar fixed-top navbar-expand-sm navbar-dark">
				
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<!-- Logo -->
				<%= link_to image_tag("logo.png", height: 50, alt: "Logo"), home_path, class: "navbar-brand" %>
				
				<!-- Links -->
				<div class="collapse navbar-collapse" id="nav-content">   
					<ul class="navbar-nav">
						<li class="nav-item">
							<%= link_to 'about', home_path+"#about", class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to 'amenities', home_path+"#amenities", class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to 'rooms', rooms_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to 'breakfast', breakfast_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to 'specials', specials_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to 'gallery', gallery_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to 'feedback', home_path+"#feedback", class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to 'contacts', home_path+"#contacts", class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to 'rates', rooms_path+"#rates", class: "nav-link" %>
						</li>
					</ul>
				</div>
			</nav>
		</div>

		<% unless notice.nil? %>
			<%= tag.div class: "alert alert-success alert-dismissible centered alert-msg" do %>
				<button type="button" class="close" data-dismiss="alert">&times;</button>
		  		<%= notice %>
		  		<%= alert %>
			<% end %>
		<% end %>
		
		<!-- The rest of the body is inserted here -->
		<%= yield %>

		<!-- CONTACTS -->
		<div class="container-fluid contacts-section largepadding grey" id="contacts">
			<h1>Contacts</h1>
			<h3>Feel free to Reach Out</h3>
			<p>Including 24hr Help and Support via our Telephone Contact</p>
			<div class="row">
				<div class="col-sm-3">
					<%= image_tag "logo.png", height: 120 %>
				</div>
				<div class="col-sm-3">
					<%= link_to 'rooms', rooms_path %><br>
					<%= link_to 'amenities', home_path+"#amenities" %><br>
					<%= link_to 'gallery', gallery_path %><br>
					<%= link_to 'location', location_path %>
				</div>
				<div class="col-sm-3">
					<h4>Address</h4>
					<p>Fortportal-Kasese Road,</p>
					<p>Fort Portal,</p>
					<p>Uganda.</p>
					<p><a href="tel:+256752755899">0752-755-899</a></p>
				</div>
				<div class="col-sm-3">
					<h4>Business Hours</h4>
					<p>MON - SUN</p>
					<p>Open 24 Hours</p>
				</div>
			</div>
		</div>

		<!-- LOCATION -->
		<div class="container-fluid location-section grey" id="location">
			<p class="greydescription">Google Map</p>

			<div class="map-responsive">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d498.69738184958993!2d30.263039035764688!3d0.6274849638796907!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1763d0c564cbfa2d%3A0xb20e45f3a713c552!2sSheevy&#39;s+Bed+%26+Breakfast!5e0!3m2!1sen!2sug!4v1521737815793" width="600" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
		</div>


		<footer>
			<p>&copy; <%= Time.new.year %> All Rights Reserved. Sheevy's Bed &amp; Breakfast. <span class="whiteImportant">v1.0.1</span></p>
		</footer>
	</div>

	<%= javascript_include_tag 'gallery' %>

	<!-- For Disqus -->
	<script id="dsq-count-scr" src="//sheevys.disqus.com/count.js" async></script>
</body>
</html>

app/views/layouts/bookings.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- for search engine description -->
	<meta name="description" content="Sheevy's Bed and Breakfast: Uganda">
	
	<title><%= @page_title %></title>
	
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'bookings' %>
	
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	<!-- Datatables -->
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
	
</head>

<body>
	<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
		<a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Dashboard</a>
		<ul class="navbar-nav px-3">
			<li class="nav-item text-nowrap">
				<% if current_user %>
					<%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "signoutlink" %>
				<% else %>	
					<% controller.redirect_to new_user_session_path %>
				<% end %>
			</li>
		</ul>
	</nav>

	<div class="container-fluid">
		<div class="row">
			<nav class="col-md-2 d-none d-md-block bg-light sidebar">
				<div class="sidebar-sticky">
					<ul class="nav flex-column">
						<li class="nav-item">
							<%= link_to "All Bookings", bookings_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to "+ New Booking", new_booking_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to "< Sheevy's Home", home_path, class: "nav-link" %>
						</li>
					</ul>
				</div>
			</nav>

			<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4 padding-bottom">
				
				<%= yield %>

			</main>
		</div>
	</div>

	<!-- Datatables -->
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function() {
		    $('#example').DataTable();
		} );
	</script>

</body>
</html>